name: oasis_taxi
description: Oasis Taxi - Aplicación de transporte
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.9
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # UI & Design
  google_fonts: ^6.2.1
  fl_chart: ^1.1.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  
  # Storage
  shared_preferences: ^2.3.4
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1  
  firebase_crashlytics: ^5.0.1
  firebase_database: ^12.0.1
  
  # OAuth y Autenticación Social
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  
  # Notifications
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Emergency System Dependencies
  flutter_phone_direct_caller: ^2.1.1
  # telephony: ^0.2.0  # DESHABILITADO TEMPORALMENTE PARA BUILD (namespace issue, discontinued)
  # sms_advanced: ^1.0.4  # TAMBIÉN CON NAMESPACE ISSUE - SMS se maneja por backend
  flutter_sound: ^9.2.13
  audio_session: ^0.2.2
  # contacts_service: ^0.6.3  # DESHABILITADO TEMPORALMENTE PARA BUILD (namespace issue)
  audioplayers: ^6.1.0
  
  # Utilities
  intl: ^0.20.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  logger: ^2.5.0
  http: ^1.2.2
  
  # FCM Real Implementation
  googleapis_auth: ^2.0.0
  dio: ^5.6.0
  
  # OTP y Verificación
  pin_code_fields: ^8.0.1
  flutter_otp_text_field: ^1.2.0
  email_validator: ^3.0.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Image
  image_picker: ^1.1.2
  
  # File Handling
  file_picker: ^10.3.3
  device_info_plus: ^12.1.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  
  # Socket.IO para tracking en tiempo real
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    # Service account credentials no van en assets por seguridad
    # - assets/oasis-taxi-peru-service-account.json